name: "Build Flipper App"

on:
  workflow_dispatch:

jobs:
  fap-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build with uFBT
        uses: flipperdevices/fbt-action@v1
        with:
          app-dir: .
          sdk-channel: release 

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Flipper-App-Build
          path: dist/*.fap
